networks:
  app-network:
    driver: bridge
volumes:
  app_data:
services:
  mysql:
    image: mysql:8.0.36-oracle
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - app_data:/var/lib/mysql